#name: Facundo Quiroga - UNLP
title: Facundo Quiroga
tagline: Sitio personal
description:  <div class="photo"> <img src="/assets/img/photo.jpg" /></div>

#theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
google_analytics: UA-179086854-1


author:
  name: Facundo Quiroga
  url: http://facundoq.github.io
paginate: 5
sidebar_home_link: false
sidebar-sticky: false
exclude:
- work.md
- vendor/bundle

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
