name: Facundo Quiroga - UNLP
title: Facundo Quiroga - UNLP
header: Facundo Quiroga

#theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
