name: Facundo Quiroga - UNLP
title: Facundo Quiroga - UNLP
header: Facundo Quiroga

theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag